import {
  Geist,
  Geist_Mono,
  Poppins,
  Cormorant_Garamond,
} from "next/font/google";
import "./globals.css";

const cormorantgaramond = Geist({
  variable: "--font-cormorant-garamond",
  weight: "400",
  subsets: ["latin"],
});

const poppins = Geist({
  variable: "--font-poppins",
  weight: ["400", "600"],
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home | Rishi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cormorantgaramond.variable} ${poppins
          .variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
